config/routes.rb
Rails.application.routes.draw do

  get root 'items#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  resources :users, only: [:show] 
  resources :items
  resources :charges
  resources :carts do
    resources :join_table_cart_items, only: [:create, :destroy]
  end
  get 'panier', to: 'carts#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :join_table_cart_items
  has_many :items, through: :join_table_cart_items

  def self.empty(user)
    JoinTableCartItem.where(cart_id: Cart.find_by(user_id: user.id).id).delete_all
  end
end

app/models/item.rb
require 'uri'

class Item < ApplicationRecord

  has_many :join_table_cart_items
  has_many :carts, through: :joint_table_cart_items

  validates :title,
    presence: true, length: { minimum: 2 }

  validates :description,
    presence: true, length: { maximum: 500 }
  
  validates :price,
    presence: true, numericality: { :greater_than_or_equal_to => 0 }

  validates :image_url,
    presence: true

end

app/models/join_table_cart_item.rb
class JoinTableCartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :item
end

app/models/join_table_order_item.rb
class JoinTableOrderItem < ApplicationRecord
    belongs_to :order
    belongs_to :item
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :user

  has_many :join_table_order_items
  has_many :items, through: :join_table_order_items

  after_create :order_send

  def order_send
    UserMailer.order_email(User.find(self.user_id)).deliver_now
    #  AdminMailer.order_email(User.find(self.user_id)).deliver_now
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :welcome_send, :create_cart

  has_one :cart
  has_many :orders

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
  

  def create_cart
    puts "Creating"
    Cart.create(user_id: self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def create
    
  end

  def edit
  end

  def update
  end

  def delete
  end

  def show
    @cart= Cart.find_by(user_id: current_user.id)
    @join_table_cart_items= JoinTableCartItem.where(cart_id: @cart.id)
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end
  
  def create
    @user = current_user
    @order = Order.create(user_id: @user.id)
    JoinTableCartItem.where(cart_id: Cart.find_by(user_id: @user.id).id).each do |x| 
      JoinTableOrderItem.create(order_id: @order.id, item_id: x.item_id)
    end
    Cart.empty(@user)
    # Amount in cents
    @amount = 500
  
    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })
  
    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'usd',
    })
  
    redirect_to root_path

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def show
    @item = Item.find_by(id: params[:id])
    unless current_user.nil?
    @cart = Cart.find_by(user_id: current_user.id)
    end
  end

end

app/controllers/join_table_cart_items_controller.rb
class JoinTableCartItemsController < ApplicationController

  # def new
  #   @cart = Cart.find(params[:cart_id])
  #   @join_table_cart_item = JoinTableCartItem.new

  # end

  def create
    @cart = Cart.find_by(user_id: current_user.id)
    @join_table_cart_item = JoinTableCartItem.new( cart_id: @cart.id, item_id: params[:item_id])

    if @join_table_cart_item.save # essaie de sauvegarder en db
      flash.notice = "join_table_cart_item successfully created"
      redirect_to panier_path
    else
      flash.alert = "join_table_cart_item not created"
      render 'new'
      flash.alert = nil
    end
  end

  def destroy
    @cart = Cart.find_by(user_id: current_user.id)
    @join_table_cart_item = JoinTableCartItem.find_by(cart_id: @cart.id, item_id: params[:item_id])
    @join_table_cart_item.destroy
    redirect_to panier_path
  end
end

app/controllers/join_table_order_items_controller.rb
class JoinTableOrderItemsController < ApplicationController

    # def new
  #   @order = Order.find(params[:order_id])
  #   @join_table_order_item = JoinTableOrderItem.new

  # end

  def create
    @order = Order.find_by(user_id: current_user.id)
    @join_table_order_item = JoinTableOrderItem.new( order_id: @order.id, item_id: params[:item_id])

    if @join_table_order_item.save # essaie de sauvegarder en db
      flash.notice = "join_table_order_item successfully created"
      redirect_to order_path(@order.id)
    else
      flash.alert = "join_table_order_item not created"
      render 'new'
      flash.alert = nil
    end
  end

  def destroy
    @order = Order.find_by(user_id: current_user.id)
    @join_table_order_item = JoinTableOrderItem.find_by(order_id: @order.id, item_id: params[:item_id])
    @join_table_order_item.destroy
    redirect_to order_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def create
    
  end

  def edit
  end

  def update
  end

  def delete
  end

  def show
    @order= Order.find_by(user_id: current_user.id)
    @join_table_order_items= JoinTableOrderItem.where(order_id: @order.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  
  def show
    @user = User.find(params[:id])
    if current_user == @user
      render 'show'
    else
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/join_table_cart_items_helper.rb
module JoinTableCartItemsHelper
end

app/helpers/join_table_order_items_helper.rb
module JoinTableOrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/carts/create.html.erb
<h1>Carts#create</h1>
<p>Find me in app/views/carts/create.html.erb</p>

app/views/carts/show.html.erb
<%total_cart_item_price = 0%>
<% @join_table_cart_items.each do |join_table_cart_item| %>

<div class="container-fluid">
    <div class="content-wrapper">
		<div class="item-container">
			<div class="container">
        <div class="card" >
          <div class="card-body">
          <% item = Item.find_by(id: join_table_cart_item.item_id) %>
          <%total_cart_item_price += item.price%>
          <img id="item-display" class="img-fluid" style="height:72px;width:50px" src=" <%= item.image_url %> ">
            item : <%= join_table_cart_item.item_id%><br/>
            cart : <%= join_table_cart_item.cart_id%><br/>
            price : <%= item.price%><br/>
          <td><%= button_to "remove from cart", cart_join_table_cart_item_path(item_id: join_table_cart_item.item_id, cart_id: join_table_cart_item.cart_id, id: join_table_cart_item.id), method: :delete , class: "btn btn-info"%></td>
          </div>
        </div>
      </div>
    </div>
      <% end %>

    <!-- stripe -->
    <div class="content-wrapper">
      <div class="item-container">
        <div class="container">
    <%= form_tag charges_path do %>
      <article>
        <% if flash[:error].present? %>
          <div id="error_explanation">
            <p><%= flash[:error] %></p>
          </div>
        <% end %>
        <label class="amount">
          <span>Amount: <%= total_cart_item_price %></span>
        </label>
      </article>
    
      <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
        data-description="Your order"
        data-amount=<%= total_cart_item_price * 100 %>
        data-locale="auto"></script>
    <% end %>

      </div>
    </div>
  </div>
</div>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>