config/routes.rb
Rails.application.routes.draw do

  get root 'items#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  resources :users, only: [:show] 
  resources :items
  resources :charges
  resources :carts do
    resources :join_table_cart_items, only: [:create, :destroy]
  end
  get 'panier', to: 'carts#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :join_table_cart_items
  has_many :items, through: :join_table_cart_items

  def self.empty(user)
    JoinTableCartItem.where(cart_id: Cart.find_by(user_id: user.id).id).delete_all
  end
end

app/models/item.rb
require 'uri'

class Item < ApplicationRecord

  has_many :join_table_cart_items
  has_many :carts, through: :joint_table_cart_items

  validates :title,
    presence: true, length: { minimum: 2 }

  validates :description,
    presence: true, length: { maximum: 500 }
  
  validates :price,
    presence: true, numericality: { :greater_than_or_equal_to => 0 }

  validates :image_url,
    presence: true

end

app/models/join_table_cart_item.rb
class JoinTableCartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :item
end

app/models/join_table_order_item.rb
class JoinTableOrderItem < ApplicationRecord
    belongs_to :order
    belongs_to :item
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :user

  has_many :join_table_order_items
  has_many :items, through: :join_table_order_items

  after_create :order_send

  def order_send
    UserMailer.order_email(User.find(self.user_id)).deliver_now
    #  AdminMailer.order_email(User.find(self.user_id)).deliver_now
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :welcome_send, :create_cart

  has_one :cart
  has_many :orders

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
  

  def create_cart
    puts "Creating"
    Cart.create(user_id: self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def create
    
  end

  def edit
  end

  def update
  end

  def delete
  end

  def show
    @cart= Cart.find_by(user_id: current_user.id)
    @join_table_cart_items= JoinTableCartItem.where(cart_id: @cart.id)
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end
  
  def create
    @user = current_user
    @order = Order.create(user_id: @user.id)
    JoinTableCartItem.where(cart_id: Cart.find_by(user_id: @user.id).id).each do |x| 
      JoinTableOrderItem.create(order_id: @order.id, item_id: x.item_id)
    end
    Cart.empty(@user)
    # Amount in cents
    @amount = 500
  
    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })
  
    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'usd',
    })
  
    redirect_to root_path

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def show
    @item = Item.find_by(id: params[:id])
    unless current_user.nil?
    @cart = Cart.find_by(user_id: current_user.id)
    end
  end

end

app/controllers/join_table_cart_items_controller.rb
class JoinTableCartItemsController < ApplicationController

  # def new
  #   @cart = Cart.find(params[:cart_id])
  #   @join_table_cart_item = JoinTableCartItem.new

  # end

  def create
    @cart = Cart.find_by(user_id: current_user.id)
    @join_table_cart_item = JoinTableCartItem.new( cart_id: @cart.id, item_id: params[:item_id])

    if @join_table_cart_item.save # essaie de sauvegarder en db
      flash.notice = "join_table_cart_item successfully created"
      redirect_to panier_path
    else
      flash.alert = "join_table_cart_item not created"
      render 'new'
      flash.alert = nil
    end
  end

  def destroy
    @cart = Cart.find_by(user_id: current_user.id)
    @join_table_cart_item = JoinTableCartItem.find_by(cart_id: @cart.id, item_id: params[:item_id])
    @join_table_cart_item.destroy
    redirect_to panier_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def create
    
  end

  def edit
  end

  def update
  end

  def delete
  end

  def show
    @order= Order.find_by(user_id: current_user.id)
    @join_table_order_items= JoinTableOrderItem.where(order_id: @order.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  
  def show
    @user = User.find(params[:id])
    if current_user == @user
      render 'show'
    else
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/join_table_cart_items_helper.rb
module JoinTableCartItemsHelper
end

app/helpers/join_table_order_items_helper.rb
module JoinTableOrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong><%= @amount %></strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-description="A month's subscription"
    data-amount="500"
    data-locale="auto"></script>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/items/index.html.erb
<div class="mx-auto" style="margin-top: 5rem; width: 500px;">
  <h1> Bienvenue sur Kitten Project !</h1>
</div>

<!-- Boucle pour presenter tous les Items -->
<div class="container">
  <div class="card-columns" style="margin-top: 5rem;">
    <% Item.all.each do |x| %>
      <p>
      <div class="card" style="width: 18rem;">
        <img class="card-img-top" src=" <%= x.image_url %> " alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title"><%= x.title %></h5>
          <p class="card-text"><%= x.description %></p>
          <h6 class="card-subtitle mb-2 text-muted"><%= x.price %></h6>
          <%= button_to "product", item_path(x.id), method: :get , class: "btn btn-info" %>
        </div>
      </div>
      </p>
    <% end %>
  </div>
</div>

app/views/items/show.html.erb
<div class="container-fluid">
    <div class="content-wrapper">
		<div class="item-container">
			<div class="container">
				<div class="col-md-12">
					<div class="product col-md-3 service-image-left">
							<img id="item-display" class="img-fluid" src=" <%= @item.image_url %> " alt="">
					</div>
				</div>
				<div class="col-md-7">
					<div class="product-title"><%= @item.title %></div>
					<div class="product-desc"><%= @item.description %></div>
					<div class="product-rating"><i class="fa fa-star gold"></i> <i class="fa fa-star gold"></i> <i class="fa fa-star gold"></i> <i class="fa fa-star gold"></i> <i class="fa fa-star-o"></i> </div>
					<hr>
					<div class="product-price">$ <%= @item.price %></div>
					<div class="product-stock">In Stock</div>
          <hr>
					<% if user_signed_in?%>
            <div class="btn-group cart">
							<td><%= button_to "add to cart", cart_join_table_cart_items_path(item_id: @item.id, cart_id: @cart.user_id), method: :post , class: "btn btn-info"%></td>
            </div>
          <%end%>
				</div>
			</div>
		</div>
		<div class="container-fluid">
			<div class="col-md-12 product-info">
					<ul id="myTab" class="nav nav-tabs nav_tabs">

						<li class="active"><a href="#service-one" data-toggle="tab">DESCRIPTION</a></li>
						<li><a href="#service-two" data-toggle="tab">PRODUCT INFO</a></li>
						<li><a href="#service-three" data-toggle="tab">REVIEWS</a></li>

					</ul>
				<div id="myTabContent" class="tab-content">
						<div class="tab-pane fade in active" id="service-one">

							<section class="container product-info">

								<h3><%= @item.description %></h3>
							</section>

						</div>
				</div>
				<hr>
			</div>
		</div>
	</div>
</div>

app/views/items/show_old.html.erb
<div class="mx-auto" style="margin-top: 5rem; width: 500px;">
  <h1> Bienvenue sur Kitten Project !</h1>
  <h6> show product page </h6>

</div>

<div class="container">
  <div class="card-columns" style="margin-top: 5rem;">
      <p>
      <div class="card" >
        <img class="card-img-top" src=" <%= @item.image_url %> " alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title"><%= @item.title %></h5>
          <p class="card-text"><%= @item.description %></p>
          <h6 class="card-subtitle mb-2 text-muted"><%= @item.price %></h6>
        </div>
      </div>
      </p>
  </div>
</div>

app/views/users/show.html.erb
<div style="margin-top: 5rem; text-align: center">
  <h1> Welcome to your profile !</h1>

    <div class="card mx-auto" style="width: 18rem; margin-top: 5rem;">
    <div class="card-body">

      
      
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><%= @user.email %></li>
        <li class="list-group-item">
          <a class="btn btn-primary" href=" <%= edit_user_registration_path %> " role="button">Edit your profile</a> </br>
        </li>
      </ul>
    </div>
  </div>
</div>

<!-- Boucle pour présenter toutes les commandes passées -->

<div class="mx-auto" style="margin-top: 5rem; text-align: center; width: 80%">
  <h1> Orders made : </h1>
  <hr>
  <div class="mb-5">
    <% Order.where(user_id: @user.id).each do |x| %>
      <h4 class="mb-2"> Order passed at <%= x.created_at %></h5>
      <% JoinTableOrderItem.where(order_id: x.id).all.each do |y| %>
        <a href=" <%= item_path(y.item_id) %> " class="list-group-item list-group-item-action">
          <div class="d-flex w-100">
          </div>
          <small> <%=Item.find(y.item_id).title%> </small>
          <small> <%=Item.find(y.item_id).price%> </small>
        </a>
      <%end%>
      </br> </br>
    <% end %>
  </div>
</div>