config/routes.rb
Rails.application.routes.draw do

  get root 'items#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  resources :users, only: [:show] 
  resources :items
  resources :charges
  resources :carts do
    resources :join_table_cart_items, only: [:create, :destroy]
  end
  get 'panier', to: 'carts#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :join_table_cart_items
  has_many :items, through: :join_table_cart_items

  def self.empty(user)
    JoinTableCartItem.where(cart_id: Cart.find_by(user_id: user.id).id).delete_all
  end
end

app/models/item.rb
require 'uri'

class Item < ApplicationRecord

  has_many :join_table_cart_items
  has_many :carts, through: :joint_table_cart_items

  validates :title,
    presence: true, length: { minimum: 2 }

  validates :description,
    presence: true, length: { maximum: 500 }
  
  validates :price,
    presence: true, numericality: { :greater_than_or_equal_to => 0 }

  validates :image_url,
    presence: true

end

app/models/join_table_cart_item.rb
class JoinTableCartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :item
end

app/models/join_table_order_item.rb
class JoinTableOrderItem < ApplicationRecord
    belongs_to :order
    belongs_to :item
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :user

  has_many :join_table_order_items
  has_many :items, through: :join_table_order_items

  after_create :order_send

  def order_send
    UserMailer.order_email(User.find(self.user_id)).deliver_now
    #  AdminMailer.order_email(User.find(self.user_id)).deliver_now
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :welcome_send, :create_cart

  has_one :cart
  has_many :orders

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
  

  def create_cart
    puts "Creating"
    Cart.create(user_id: self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def create
    
  end

  def edit
  end

  def update
  end

  def delete
  end

  def show
    @cart= Cart.find_by(user_id: current_user.id)
    @join_table_cart_items= JoinTableCartItem.where(cart_id: @cart.id)
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end
  
  def create
    @user = current_user
    @order = Order.create(user_id: @user.id)
    JoinTableCartItem.where(cart_id: Cart.find_by(user_id: @user.id).id).each do |x| 
      JoinTableOrderItem.create(order_id: @order.id, item_id: x.item_id)
    end
    Cart.empty(@user)
    # Amount in cents
    @amount = 500
  
    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })
  
    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'usd',
    })
  
    redirect_to root_path

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def show
    @item = Item.find_by(id: params[:id])
    unless current_user.nil?
    @cart = Cart.find_by(user_id: current_user.id)
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def create
    
  end

  def edit
  end

  def update
  end

  def delete
  end

  def show
    @order= Order.find_by(user_id: current_user.id)
    @join_table_order_items= JoinTableOrderItem.where(order_id: @order.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  
  def show
    @user = User.find(params[:id])
    if current_user == @user
      render 'show'
    else
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/join_table_cart_items_helper.rb
module JoinTableCartItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" id="test" href="<%= root_path %>">Kitten project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor02">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="<%= root_path %>">Home</a>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <a class="nav-link" href="<%= panier_path %>">Cart</a>
        </li>
      <% end %>
      <li class="nav-item dropdown">
      <% if user_signed_in? %>
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        User account / Sign Out
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="<%= user_path(current_user.id) %>">Account</a>
          <a class="dropdown-item" href="<%=  destroy_user_session_path %>" data-method="DELETE">Sign out</a>
        </div>
      <% else %>
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Sign up / sign in
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="<%=new_user_registration_path%>">Sign up</a>
          <a class="dropdown-item" href="<%=user_session_path%>">Sign in</a>
        </div>
      <% end %>
      </li>
    </ul>
  </div>
</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjetChaton</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.0/minty/bootstrap.min.css" rel="stylesheet" integrity="sha384-HqaYdAE26lgFCJsUF9TBdbZf7ygr9yPHtxtg37JshqVQi6CCAo6Qvwmgc5xclIiV" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>